### ISSUE TITLE
Propose solution for blogging to site

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#10]
The team would like to be able to publish content both to Medium as well as our own site for SEO purposes.

We need to create a solution with a CMS that allows for a webhook to be created and a build to be generated automatically upon changes to the CMS content.  

Ideally we select a CMS that a non technical user is able to publish content to, so all of our team members are able to generate content.

**Comment by vikaskyadav** [comment]
We can use WordPress as CMS for the website. Plus, it will be easy to import posts from medium. Additionally, Gutenberg editor is expected to come as a stable version which really will enhance the usability for non-technical users.

**Comment by pelsasser** [comment]
@vikaskyadav your suggesting a wordpress blog that we link to the main site?

**Comment by vikaskyadav** [comment]
yeah. something like that. It will be easy to manage this way as you are
also emphasizing on usability aspects.

**Comment by 42piratas** [comment]
@pelsasser I didn't get it the part *"a wordpress blog that we link to the main site"*. The wordpress could simply be an invisible part of the main website, delivering pages either as
 
`marketprotocol.io/article-canonical-url` 
`marketprotocol.io/job-post-canonical-url` 
`marketprotocol.io/newsletter-canonical-url` 

or 

`marketprotocol.io/blog/article-canonical-url` 
`marketprotocol.io/jobs/job-post-canonical-url` 
`marketprotocol.io/newsletter/newsletter-canonical-url` 

or am I missing something?

**Comment by pelsasser** [comment]
@42piratas - you probably are correct, I don't have much word press experience.

Some solutions / examples I have come across - 

https://github.com/DanWebb/danwebb.co
https://react-static.js.org/docs/concepts/#using-a-cms

**Comment by pelsasser** [comment]
@eswarasai @42piratas @rojosnow @nitinrgupta - I am going to stake #129 as see how that works out as a proposed solution unless someone thinks this is a bad way to go. 

I think this is lightweight and should suffice for all of our SEO needs without a full blown CMS solution. 

please let me know thoughts before I stake it.

**Comment by rojosnow** [comment]
If looking at a non-Wordpress/Drupal CMS, you're in the realm of https://www.staticgen.com and https://headlesscms.org. I think it's best to look at the path of least resistance and where we could find lots of devs to work on this.

As far as URLs, TLD & subdomains are easy to manage...but we don't want to do that here due to SEO. So, once you're after the leading slash, `/` and embedding the site under the domain, there's an issue of routing. DNS doesn't handle "subdirectory" routing so you're options are apache/nginx, the native routing in the CMSes, or a custom solution as part of marketprotocol.io.

The question is where do you want this to occur? It has to be a canonical place (all traffic is routed through it) to avoid duplicate URLs. If apache/nginx, we spin up a proxy on AWS. If Wordpress/Drupal, they have routing/redirection built-in, and if custom, we're into React Router to handle these special routes. 

apache/nginx probably makes the most sense. Then, we can use whatever CMS or static-gen/headless CMS we want. Since Medium is important, I would choose something that has an existing integration. Looks like both WordPress and Drupal have that. Since Medium has an API, I'm sure I could find other integrations.

I would be curious to see what somebody would come back with. @pelsasser, I agree. I think we can find something simple. I would probably spec it out as looking for a React based solution to leverage everything else we are doing.

**Comment by pelsasser** [comment]
@rojosnow - thanks for the thoughtful response.

https://github.com/DanWebb/danwebb.co - seems like a very simple way to do this given our existing infrastructure, which is the main reason I think it is worth heading down this path.

I already attempted the cross posting with medium as a test, and it is very straightforward and our community managers could easily handle it.

**Comment by 42piratas** [comment]
@pelsasser Unfortunately, I cannot take part in the discussion as I am familiar only with Wordpress. 

That said, danwebb.co looks very nice.

**Comment by pelsasser** [comment]
one other option that is netlify CMS, it will give the ability to make edits to our non dev users as well, which is nice. 

Here is an example integration with a react-static site. 
https://github.com/nozzle/react-static/tree/master/examples/netlifycms

**Comment by pelsasser** [comment]
closing for #136
