### ISSUE TITLE
[General] Optimizations for faster load times

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#37]
### User Story

Our site is being accessed from all over the world, and it would be nice to optimize it slightly for places with slower connects. 

### Why Is this Needed?

*Summary*: Important for first impressions from users 
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

https://developers.google.com/speed/pagespeed/insights/?url=www.marketprotocol.io&tab=desktop

### Current Behavior
Low optimization scores

### Expected Behavior
High optimization scores

### Reproduction

https://developers.google.com/speed/pagespeed/insights/?url=www.marketprotocol.io&tab=desktop

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

**Comment by brentoneill** [comment]
After looking at the Google Page Speed page, it looks like the remaining optimizations to be made are on the server side: Browser Caching and Compression (gZip)

**Comment by eswarasai** [comment]
@brentoneill -- A little bit about how the `website` is actually deployed. It's a AWS S3 bucket being served through CloudFront.

As mentioned in the below article we need to send the Accept-Content Header in order to enable compression I guess. Not really sure how can it be done, but feel free to suggest your ideas here -- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by pelsasser** [comment]
@rojosnow - since you have a pretty good handle on what is needed here, can you help to build out the issue so we can push a bounty out there to get it worked on

**Comment by pelsasser** [comment]
closing - due to other priorities.
