### ISSUE TITLE
[SEO] site content

### ISSUE THREAD

**Issue by pchuck** [MARKETProtocol/website#62]
### Why Is this Needed?

*Summary*: Increasingly, search engines use natural language processing to weigh content over links when evaluating the quality and authority of a given site. Sites with more unique and quality content rank higher in search results.

### Description

*Type*: Enhancement

### Solution

Consider moving some of the innovative content unique to MARKET Protocol into the main site/pages and/or elaborate on this content in pages on the site. Doing so may improve the amount of searchable quality content on the site and improve search placement.

**Comment by 42piratas** [comment]
My 2 cents: rather than moving the content to the main website, prioritize the implementation of a CMS and cross-post content e.g. with Medium. Besides, as mentioned before, the CMS also could help with  the `newsletter` and `jobs` sections (/blog, /newsletters, /jobs).

That said, we must keep in mind cross-posting good practices, e.g: 
https://help.medium.com/hc/en-us/articles/217991468-SEO-and-duplicate-content
